#nginx-proxy-manager docker compose file:
version: '3.3'

services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /var/server/proxy/data:/data
      - /var/server/proxy/letsencrypt:/etc/letsencrypt